name: First Workflow

on: [ push ]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello world"
      - name: Multiline Command
        run: |
          echo "ğŸ‚"
          echo "ğŸ‡"
          echo "ğŸ‡ 2"
          echo "ğŸ‡ 3"
      
  parallel-job_macos:
    runs-on: macos-latest
    steps:
     - name: View SW Version
       run: sw_vers
  
  dependent-job:
    runs-on: windows-latest
    needs: run-shell-commands
    steps:
      - name: echo a string windows
        run: Write-Output "Windows string"